import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import Script from "next/script";
import "./globals.css";
import { AuthInit } from "@/features/auth/AuthInit";
import { TonConnectProvider } from "@/shared/providers/TonConnectProvider";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

declare global {
  interface Window {
      Telegram?: {
          WebApp?: {
              ready(): unknown;
              initData: string;
              initDataUnsafe?: {
                  user?: {
                      id: number;
                      first_name: string;
                      username:string;
                      photo_url:string;
                  };
              };
              HapticFeedback?: {
                  impactOccurred: (style: 'light' | 'medium' | 'heavy') => void;
              };
              disableVerticalSwipes: () => void;
              shareToStory: (options: {
                media_url: string;
                text: string;
                widget_link: {
                  url: string;
                  name: string;
                };
              }) => void;
              expand: () => void;
              isExpanded?: boolean;
              onEvent: (event: string, callback: (data: Record<string, unknown>) => void) => void;
              offEvent: (event: string) => void;
          };
      };
      TelegramWebviewProxy?: {
          postEvent: (eventType: string, eventData: unknown) => void;
      };
  }
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Manifest URL для TonConnect (храним в public/tonconnect-manifest.json)
  // Если нужен абсолютный URL (production), можно переопределить через NEXT_PUBLIC_TONCONNECT_MANIFEST_URL
  const manifestUrl = process.env.NEXT_PUBLIC_TONCONNECT_MANIFEST_URL || '/tonconnect-manifest.json';
  
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} antialiased`}
      >
        <Script
          src="https://telegram.org/js/telegram-web-app.js"
          strategy="afterInteractive"
        />
        <TonConnectProvider manifestUrl={manifestUrl}>
          <AuthInit />
          {children}
        </TonConnectProvider>
      </body>
    </html>
  );
}
