import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import Script from "next/script";
import "./globals.css";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

declare global {
  interface Window {
      Telegram?: {
          WebApp?: {
              ready(): unknown;
              initData: string;
              initDataUnsafe?: {
                  user?: {
                      id: number;
                      first_name: string;
                      username:string;
                  };
              };
              HapticFeedback?: {
                  impactOccurred: (style: 'light' | 'medium' | 'heavy') => void;
              };
              disableVerticalSwipes: () => void;
              shareToStory: (options: {
                media_url: string;
                text: string;
                widget_link: {
                  url: string;
                  name: string;
                };
              }) => void;
              expand: () => void;
              isExpanded?: boolean;
              onEvent: (event: string, callback: (data: Record<string, unknown>) => void) => void;
              offEvent: (event: string) => void;
          };
      };
      TelegramWebviewProxy?: {
          postEvent: (eventType: string, eventData: unknown) => void;
      };
  }
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} antialiased`}
      >
        <Script
          src="https://telegram.org/js/telegram-web-app.js"
          strategy="afterInteractive"
        />
        {children}
      </body>
    </html>
  );
}
